config/routes.rb
Rails.application.routes.draw do

  get 'en/index'

  get 'en/solution'

  get 'en/rates'

  get 'en/contact'

  get 'ua/index'

  get 'ua/solution'

  get 'ua/rates'

  get 'ua/contact'

  get 'ru/index'

  get 'ru/solution'

  get 'ru/rates'

  get 'ru/contact'

  get 'rate_form/encreate'
  get 'rate_form/rucreate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

    root 'ua#index'
    
    resources :contacts, only: [:new, :create, :index]
    resources :ua_rates, only: [:new, :create, :index, :show]
    resources :ru_rates, only: [:new, :create, :index, :show]
    resources :en_rates, only: [:new, :create, :index, :show]
    resources :rate_form, only: [:new, :create, :index, :delete, :encreate]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   user ||= User.new # guest user (not logged in)
   can :read, :all
    if user && user.admin?
      can :manage, :all
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :ua
	belongs_to :ru
	belongs_to :en

	validates :nickname,  presence: true 
	validates :mail,  format: { with:  /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
	validates :theme, presence: true 
  	validates :text , presence: true 

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  #def headers
   ###### end
end

app/models/en.rb
class En < ActiveRecord::Base
	has_many :contacts
	has_many :en_rates
end

app/models/en_rate.rb
class EnRate < ActiveRecord::Base
	belongs_to :en
	has_many :rate_forms
end

app/models/rate_form.rb
class RateForm < ActiveRecord::Base
	has_many :ru_rate
	has_many :ua_rate
	has_many :en_rate
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users

  validates :name, presence: true, uniqueness: true

end

app/models/ru.rb
class Ru < ActiveRecord::Base
	has_many :contacts
	has_many :ru_rates
end

app/models/ru_rate.rb
class RuRate < ActiveRecord::Base
	belongs_to :ru
	has_many :rate_forms
end

app/models/ua.rb
class Ua < ActiveRecord::Base
	has_many :contacts
	has_many :ua_rates
end

app/models/ua_rate.rb
class UaRate < ActiveRecord::Base
	belongs_to :ua
	has_many :rate_forms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  def admin?
    role_id == 1
  end
end

app/controllers/en_controller.rb
class EnController < ApplicationController
  def index
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def solution
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def rates
    @enrates = EnRate.all
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def contact
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end
end

app/controllers/rate_form_controller.rb
class RateFormController < ApplicationController
  def new
  	@rateform = RateForm.new
  end

  def create
    @rateform = RateForm.new(rate_params)
    if @rateform.save
      redirect_to :root
      RateFormMailer.rate_email(@rateform).deliver_now
    end
  end

  def encreate
     @rateform = RateForm.new
      RateFormMailer.rate_email(@rateform).deliver_now
     # ContactsMailer.sample_email(@contact).deliver_now
  end

  def rucreate
     @rateform = RateForm.new
      RateFormMailer.rate_email(@rateform).deliver_now
     # ContactsMailer.sample_email(@contact).deliver_now
  end



  private
  def rate_params 
    params.require(:rate_form).permit(:name, :mail, :comment, :ratename, :phone)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/en_helper.rb
module EnHelper
end

app/helpers/en_rates_helper.rb
module EnRatesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/ru_helper.rb
module RuHelper
end

app/helpers/ru_rates_helper.rb
module RuRatesHelper
end

app/helpers/ua_helper.rb
module UaHelper
end

app/helpers/ua_rates_helper.rb
module UaRatesHelper
end

app/views/rate_form/_ua_rate_form.html.erb
h1 Contact
= simple_form_for @contact,  url: contacts_path do |f|
	= f.input :nickname, placeholder: 'Имья', :error => false, :label => false
	= f.input :mail, placeholder: 'Пошта', :error => false, :label => false
	= f.input :theme, placeholder: 'Тема', :error => false, :label => false
	= f.input :text, placeholder: 'Текст пов1домлення', :error => false, :label => false


	.form-actions
		= f.button :submit, 'В1д1слати'

app/views/rate_form/create.html.erb
<h1>RateForm#create</h1>
<p>Find me in app/views/rate_form/create.html.erb</p>

app/views/rate_form/encreate.html.slim
div.new_message
	div.span6.offset3
= simple_form_for @rateform, url: rate_form_index_path  do |f|
		p 
			b Name	
		= f.input :name, placeholder: 'Імя', :error => false, label: false
		p
			b Email
		= f.input :mail , :error => false, label: false
		p
			b Message
		= f.input :comment, :error => false, label: false, as: :text
		p
			b Rate
		= f.input :ratename, collection: [ "Minimum", "Optimum", "Maximum"], :error => false, label: false, :class => "tariftype"
		p
			b Phone nubmer
		= f.input :phone, :error => false, label: false


		= f.button :submit, "Send", :class => "ratebutton"


 

app/views/rate_form/new.html.slim
div.new_message
	div.span6.offset3
= simple_form_for @rateform, url: rate_form_index_path  do |f|
		p 
			b Ім'я	
		= f.input :name, placeholder: 'Імя', :error => false, label: false
		p
			b Пошта
		= f.input :mail , :error => false, label: false
		p
			b Повидомлення
		= f.input :comment, :error => false, label: false, as: :text
		p
			b Тариф
		= f.input :ratename, collection: [ "Мінімальний", "Оптимальний", "Максимальний"], :error => false, label: false, :class => "tariftype"
		p
			b Телефон
		= f.input :phone, :error => false, label: false


		= f.button :submit, "Відправити", :class => "ratebutton"


 

app/views/rate_form/rucreate.html.slim
div.new_message
	div.span6.offset3
= simple_form_for @rateform, url: rate_form_index_path  do |f|
		p 
			b Имя	
		= f.input :name, placeholder: 'Імя', :error => false, label: false
		p
			b Почта
		= f.input :mail , :error => false, label: false
		p
			b Сообщение
		= f.input :comment, :error => false, label: false, as: :text
		p
			b Тариф
		= f.input :ratename, collection: [ "Мінімальний", "Оптимальний", "Максимальний"], :error => false, label: false, :class => "tariftype"
		p
			b Телефон
		= f.input :phone, :error => false, label: false


		= f.button :submit, "Отправить", :class => "ratebutton"


 