config/routes.rb
Rails.application.routes.draw do

  get 'en/index'

  get 'en/solution'

  get 'en/rates'

  get 'en/contact'

  get 'ua/index'

  get 'ua/solution'

  get 'ua/rates'

  get 'ua/contact'

  get 'ru/index'

  get 'ru/solution'

  get 'ru/rates'

  get 'ru/contact'

  get 'rate_form/encreate'
  get 'rate_form/rucreate'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

    root 'ua#index'
    
    resources :contacts, only: [:new, :create, :index]
    resources :ua_rates, only: [:new, :create, :index, :show]
    resources :ru_rates, only: [:new, :create, :index, :show]
    resources :en_rates, only: [:new, :create, :index, :show]
    resources :rate_form, only: [:new, :create, :index, :delete, :encreate]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   user ||= User.new # guest user (not logged in)
   can :read, :all
    if user && user.admin?
      can :manage, :all
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :ua
	belongs_to :ru
	belongs_to :en

	validates :nickname,  presence: true 
	validates :mail,  format: { with:  /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
	validates :theme, presence: true 
  	validates :text , presence: true 

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  #def headers
   ###### end
end

app/models/en.rb
class En < ActiveRecord::Base
	has_many :contacts
	has_many :en_rates
end

app/models/en_rate.rb
class EnRate < ActiveRecord::Base
	belongs_to :en
	has_many :rate_forms
end

app/models/rate_form.rb
class RateForm < ActiveRecord::Base
	has_many :ru_rate
	has_many :ua_rate
	has_many :en_rate
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users

  validates :name, presence: true, uniqueness: true

end

app/models/ru.rb
class Ru < ActiveRecord::Base
	has_many :contacts
	has_many :ru_rates
end

app/models/ru_rate.rb
class RuRate < ActiveRecord::Base
	belongs_to :ru
	has_many :rate_forms
end

app/models/ua.rb
class Ua < ActiveRecord::Base
	has_many :contacts
	has_many :ua_rates
end

app/models/ua_rate.rb
class UaRate < ActiveRecord::Base
	belongs_to :ua
	has_many :rate_forms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  def admin?
    role_id == 1
  end
end

app/controllers/en_controller.rb
class EnController < ApplicationController
  def index
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def solution
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def rates
    @enrates = EnRate.all
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end

  def contact
    @contact = Contact.new
    if @contact.save
      redirect_to :root
      ContactsMailer.sample_email(@contact).deliver_now
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/en_helper.rb
module EnHelper
end

app/helpers/en_rates_helper.rb
module EnRatesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/ru_helper.rb
module RuHelper
end

app/helpers/ru_rates_helper.rb
module RuRatesHelper
end

app/helpers/ua_helper.rb
module UaHelper
end

app/helpers/ua_rates_helper.rb
module UaRatesHelper
end

app/views/layouts/_header.html.erb
<%if action_name == 'index' %>
  <div class="main_header_bg" id="main_head">
<% end %>
  <header id='header'>
    <div class="container">
      <div class="logo">
        <%= link_to image_tag('logo.png'), root_path%>
      </div>
      <nav class="navigation">
        <div id = 'ChangeLang'>
        <%= link_to image_tag('ru.png'), ru_index_path  %>
        <%= link_to image_tag('ua.png'), ua_index_path  %>
        <%= link_to image_tag('en.png'), en_index_path  %>
        </div>
        <% if controller_name == 'ua'%>
          <ul>
            <li><%= link_to 'Головна', ua_index_path %></li>
            <li><%= link_to 'Готові рішення', ua_solution_path %></li>
            <li><%= link_to 'Тарифи', ua_rates_path %></li>
            <li><%= link_to 'Контакти', ua_contact_path %></li>
            <% if user_signed_in? %>
                <li>
                <%= link_to('Вихід', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Вхід', new_user_session_path)  %>  
                </li>
              <% end %>
          </ul>
        <% elsif controller_name == 'ru' %>
          <ul>
            <li><%= link_to 'Главная', ru_index_path %></li>
            <li><%= link_to 'Готовые решения', ru_solution_path %></li>
            <li><%= link_to 'Тарифы', ru_rates_path %></li>
            <li><%= link_to 'Контакты', ru_contact_path %></li>
            <% if user_signed_in? %>
                <li>
                <%= link_to('Виход', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Вход', new_user_session_path)  %>  
                </li>
              <% end %>
          </ul>
        <% elsif controller_name == 'en' %>
          <ul>
            <li><%= link_to 'Main', en_index_path %></li>
            <li><%= link_to 'Solution', en_solution_path %></li>
            <li><%= link_to 'Rate', en_rates_path %></li>
            <li><%= link_to 'Contacts', en_contact_path %></li>
            <% if user_signed_in? %>
                <li>
                <%= link_to('Log out', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Log in', new_user_session_path)  %>  
                </li>
              <% end %>
          </ul>
        <% end %>
        <div class="clear"></div>
      </nav>
      <div class="nav_button">
        <div class="nav_button_line"></div>
        <div class="nav_button_line"></div>
        <div class="nav_button_line"></div>
      </div>
    </div>
    <% if controller_name == 'ua' && controller.action_name == 'index'%>
      <div class="main_header_text container"><h2>Зробіть життя своїх</br> клієнтів простішим</h2></div>
    <% end %>  
    <% if controller_name == 'ru' && controller.action_name == 'index'%>
      <div class="main_header_text container"><h2>Сделайте жизнь своих</br> клиентов проще</h2></div>
    <% end %> 
    <% if controller_name == 'en' && controller.action_name == 'index'%>
      <div class="main_header_text container"><h2>Make your life</br> customers easier</h2></div>  
    <% end %>
  </header>
<%if action_name == 'index' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="ru"> <!--<![endif]-->
<head>

  <meta charset="utf-8">

  <title>Ipass</title>
  <meta name="description" content="">

  <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" href="img/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-touch-icon-114x114.png">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link href="http://allfont.ru/allfont.css?fonts=pt-sans" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <!-- <div id = 'ChangeLang'>
		<%#= link_to image_tag('ru.png'), ru_index_path  %>
		<%#= link_to image_tag('ua.png'), ua_index_path  %>
		<%#= link_to image_tag('en.png'), en_index_path  %>
	</div> -->

  <div class="container-fluid">
    <%= render partial: 'layouts/header' %>

    <div class="content_container">
      <%= yield %>
    </div>
   
        <% if controller_name == 'ua'%>
          <%=  render :partial => 'contacts/uanew'%>
        <% elsif controller_name == 'ru' %>  
          <%=  render :partial => 'contacts/runew'%>
        <% elsif controller_name == 'en' %>  
          <%=  render :partial => 'contacts/ennew'%>  
        <% end %>
        </div>
    
  </div>

  <a class="scroller" id="scroller" href="#header">&uArr;</a>

	<div class="hidden"></div>

	<div class="loader">
		<div class="loader_inner"></div>
	</div>
	<div class="mobile_navigation"></div>

</body>
</html>